# gitea CONFIGURATION
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitea-vol
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/gitea
  storageClassName: standard
---
apiVersion:  v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: gitea-vol
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
        - name: gitea
          image: 'gitea/gitea'
          env:
          - name: USER_UID
            value: "1000"
          - name: USER_GID
            value: "1000"
          - name: APP_NAME
            value: "Git"
          - name: RUN_MODE
            value: "prod"
          - name: GITEA__database__DB_TYPE
            value: "postgres"
          - name: GITEA__database__HOST
            value: "postgres"
          - name: GITEA__database__NAME
            value: "giteaprod"
          - name: GITEA__database__USER
            valueFrom:
              secretKeyRef:
                key: POSTGRES_USER
                name: postgres
          - name: GITEA__database__PASSWD
            valueFrom:
              secretKeyRef:
                key: POSTGRES_PASSWORD
                name: postgres
          resources:
            limits:
              memory: 1Gi
              cpu: 1000m
          ports:
            - containerPort: 3000
              name: gitea-gui
            - containerPort: 22
              name: gitea-ssh
          volumeMounts:
            - name: gitea-data
              mountPath: /data
      volumes:
      - name: gitea-data
        persistentVolumeClaim:
          claimName: gitea-claim
---
apiVersion: v1
kind: Service
metadata:
  name: gitea
spec:
  selector:
    app: gitea
  ports:
  - name: gitea-gui
    port: 3000
    targetPort: 3000
  - name: gitea-ssh
    port: 22
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitea
  #annotations:
  #  nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: beutler.git.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gitea
                port:
                  name: gitea-gui
---
# Database Configuration
# Source https://gist.github.com/ivanbrennan/cf20e26de6e7cbf517d101e7cc9d4ca0
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/postgres
  storageClassName: standard
---
apiVersion:  v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: postgres
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres
type: Opaque
data:
  POSTGRES_USER: Z2l0ZWFwcm9k     # printf giteaprod | base64
  POSTGRES_PASSWORD: cGFzc3dvcmQ= # printf password | base64
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  labels:
    app: postgres
    role: service
spec:
  replicas: 1
  serviceName: postgres
  selector:
    matchLabels: 
      app: postgres
      role: service
  template:
    metadata:
      labels:
        app: postgres
        role: service
    spec:
      containers:
        - name: postgres
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          image: postgres:9.6
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_USER
                  name: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: postgres
          ports:
            - containerPort: 5432
              name: postgres
              protocol: TCP
          volumeMounts:
            - name: postgres
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres
          persistentVolumeClaim:
            claimName: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
    role: service
spec:
  selector:
    app: postgres
    role: service
  type: NodePort
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
